# .swiftlint.yml

disabled_rules:
  - identifier_name
  - function_body_length
  - line_length
  - type_body_length
  - multiple_closures_with_trailing_closure
  - file_length
  - cyclomatic_complexity
  - nesting
